name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '💥 Breaking Changes'
    labels:
      - 'breaking'
  - title: '🔒️ Security'
    labels:
      - 'security'
  - title: '✨ Features'
    labels:
      - 'feature'
  - title: '👽️ API'
    labels:
      - 'api'
  - title: '⚡ Enhancement'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
  - title: '✅ Testing'
    labels:
      - 'testing'
  - title: '🆙 Dependencies Update'
    labels:
      - 'dependencies'
  - title: 'Misc'
    labels:
      - 'misc'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'exclude from changelog'
template: |
  ## Changes
  <!-- ここに主要な変更点をまとめる -->
  $CHANGES
