name: Automatic Rebase and Create Pull Request
on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

    
jobs:
  create_pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.base.ref,'releases/')
    permissions:
      contents: 'write'
      pull-requests: 'write'
      
    steps:
      - name: Check env
        run: |
          echo ${{ github.event.pull_request.base.ref }}
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ github.event.pull_request.head.sha }}
          git checkout ${{ github.event.pull_request.head.sha }}
          git checkout -b releases/${{ github.sha }} 
          git push origin releases/${{ github.sha }}:hotfix/release_${{ github.event.pull_request.head.ref }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: hotfix/release_${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Create Pull Request
        run: gh pr create -B "main" -t "[Auto Generated] ${{ github.event.pull_request.title }}" -b "${{ github.event.pull_request.body }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  rebase:
    name: Rebase
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.head.ref,'hotfix/release_')
    permissions:
      contents: 'write'
      pull-requests: 'write'
      
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}