name: main

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: test
  IMAGE_TAG: main

jobs:
  image:
    name: Build Docker Image (main)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: hijiki51
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/hijiki51/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}