name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          config-name: minor-release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c releases/${{ steps.release-drafter.outputs.tag_name }}
          git push -u origin releases/${{ steps.release-drafter.outputs.tag_name }}
