name: Release Drafter

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  update_minor_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          config-name: minor-release.yml
          commitish: releases/v${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Parse semver string
        id: semver
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.release-drafter.outputs.tag_name }}
          version_extractor_regex: 'v(.*)$'
      - name: Create new branch or switch to existing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c releases/${{ github.sha }}
          git push -f origin releases/${{ github.sha }}:releases/v${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.x
