name: Release Drafter

on:
  push:
    branches:
      - releases/*
  workflow_dispatch:

jobs:
  update_patch_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: patch-release.yml
          commitish: ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
